/**
 * Public lifecycle and gameplay boundaries for the Minecraft preview runtime.
 *
 * Kernel owns Minecraft vocabulary and mc-sim owns reusable state transitions;
 * this package owns the orchestration and the world-bound gameplay verbs that
 * connect them. The portable mc-kernel and mc-sim surfaces are re-exported
 * directly, while physics, save, and generated-world surfaces are exposed as
 * namespaces to keep upstream domains distinct from this package's local
 * sparse-world and lifecycle boundaries.
 */

export * from './domain/boot-phase.js'
export * from './domain/launch-options.js'
export * from './domain/block-interaction.js'
export * from './domain/block-targeting.js'
export * from './domain/physics-world.js'
export * from './domain/flat-chunk.js'
export * from './domain/explosion-interaction.js'
export * from './domain/crop-interaction.js'
export * from './domain/furnace-interaction.js'
export * from './domain/projectile-interaction.js'
export * from './domain/wither-interaction.js'

export * from '@nerima-games/mc-kernel'
export { isEmpty } from '@nerima-games/mc-sim'
export { isEmpty as isEmptyBlockState } from '@nerima-games/mc-kernel'
export * from '@nerima-games/mc-sim'
// Mc-kernel 0.8.0 now publishes the canonical item-stack inventory helper.
// Select it explicitly where the broad sim re-export has the same name.
export { addItemStack } from '@nerima-games/mc-kernel'
// Kernel absorbs vocabulary that this package's own local domain
// Modules already implement (redstone/fluid mechanics, PlayerPose). Explicit
// Re-exports below pick the owner, this package's local module.
export type {
  BlockReader,
  BlockSource,
  BlockWorld,
  FlowingFluidKind,
  FluidCell,
  FluidChange,
  FluidLevel,
  FluidState,
  FluidUpdate,
  HorizontalRedstoneFace,
  RedstoneChange,
  RedstoneComparator,
  RedstoneComparatorMode,
  RedstoneDevice,
  RedstoneDeviceStateUpdate,
  RedstoneObserver,
  RedstonePower,
  RedstoneRepeater,
  RedstoneRepeaterTimer,
  RedstoneState,
  RedstoneUpdate,
  RepeaterDelayTicks,
} from './domain/block-interaction.js'

export {
  FLOWING_FLUID_LEVEL,
  FLUID_BLOCK_IDS,
  FLUID_LEVEL_MAX,
  FLUID_LEVEL_MIN,
  FLUID_LEVEL_STEP,
  FLUID_MIX_BLOCK_IDS,
  REDSTONE_BLOCK_IDS,
  REDSTONE_POWER_MAX,
  REDSTONE_POWER_MIN,
  REDSTONE_POWER_STEP,
  REDSTONE_REPEATER_DELAY_MAX_TICKS,
  REDSTONE_REPEATER_DELAY_MIN_TICKS,
  SOURCE_FLUID_LEVEL,
  blockAt,
  blockIdOfFluidKind,
  blockLightAt,
  blockReaderOf,
  canFluidReplace,
  clearFluidCell,
  clearRedstoneDevice,
  clearRedstoneInput,
  emptyBlockWorld,
  emptyFluidState,
  emptyRedstoneState,
  fluidCellAt,
  fluidKindOfBlockId,
  fluidLevel,
  fluidStateFromWorld,
  readBlockAt,
  redstoneComparator,
  redstoneDeviceAt,
  redstoneDevicePowerAt,
  redstoneInputAt,
  redstoneObserver,
  redstonePower,
  redstonePowerAt,
  redstoneRepeater,
  repeaterDelayTicks,
  scheduleFluidAt,
  setBlockAt,
  setFluidCell,
  setRedstoneDevice,
  setRedstoneInput,
  unscheduleFluidAt,
  updateFluids,
  updateRedstone,
  withRedstoneDeviceState,
  withRedstoneWirePowers,
} from './domain/block-interaction.js'

export type {
  PlayerPose,
} from './domain/block-targeting.js'

// Kernel also absorbs entity/inventory/equipment/weather/wither/
// Vehicle/recipe/vitals/hotbar/crafting/projectile/primed-tnt/smelting/
// Statistics/enchantment/crop/brewing/damage vocabulary that mc-sim already
// Owned as its own state-transition types before that release. Every one of
// These names is what this package's own domain and application modules
// Already import from mc-sim, so mc-sim keeps the name; mc-kernel's same-named
// Export is reachable only through its own namespace import.
export type {
  DespawnOutcome,
  Durability,
  EnchantmentTableCost,
  EnchantmentTableItem,
  EnchantmentTableOffer,
  EnchantmentTableOffers,
  EnchantmentTableRandom,
  EnchantmentTableRuleId,
  EnchantmentTableSlot,
  Entity,
  EntityRoster,
  EntityState,
  EntityStep,
  EntityTransition,
  Equipment,
  EquipmentDefinition,
  EquipmentItem,
  EquipmentOutcome,
  EquipmentSlot,
  EquipmentSlots,
  EquipmentValidationError,
  EquipmentValidationResult,
  EquippableItemType,
  ExplosionBlock,
  ExplosionBlockPosition,
  ExplosionBlockReader,
  ExplosionCommit,
  ExplosionEntity,
  ExplosionEntityEffect,
  ExplosionLimits,
  ExplosionMutation,
  ExplosionPlan,
  ExplosionRequest,
  FoodTickSignal,
  FuelRule,
  FurnaceState,
  GenerateEnchantmentOffersInput,
  Ingredient,
  Inventory,
  ItemDurabilityDefinition,
  ItemStack,
  MissingIngredient,
  NormaliseOutcome,
  NormaliseRosterOutcome,
  PatternCell,
  PlaceableBlock,
  PrimedTntCommit,
  PrimedTntMutation,
  PrimedTntPlan,
  PrimedTntRequest,
  PrimedTntState,
  ProjectileEntity,
  ProjectileHit,
  ProjectileStep,
  ProjectileWorld,
  Recipe,
  RecipeConflict,
  RecipeId,
  RecipeMatch,
  RecipePattern,
  RecipeTable,
  RemoveAtOutcome,
  RemoveAtResult,
  RemoveOutcome,
  RosterRepair,
  ShapedRecipe,
  ShapelessRecipe,
  Slot,
  SmeltingRecipe,
  SpawnOutcome,
  SpawnRequest,
  StatisticKey,
  Statistics,
  SupportedVanillaEnchantmentId,
  SweepOutcome,
  TimeState,
  ValidEquipmentItem,
  VanillaAnvilCost,
  VanillaEnchantmentTableRule,
  Vehicle,
  VehicleSnapshot,
  VehicleType,
  VehicleValidationError,
  VehicleValidationResult,
  VehicleVelocity,
  Vitals,
  VitalsView,
  Weather,
  WeatherState,
  WitherDamageKind,
  WitherDamageResult,
  WitherDeathDescriptor,
  WitherPhase,
  WitherSkullProjectileDescriptor,
  WitherSkullVariant,
  WitherSnapshot,
  WitherState,
  WitherStep,
  WitherSummonMatch,
  WitherSummonMaterial,
} from '@nerima-games/mc-sim'
export {
  addBrewingFuel,
  addExhaustion,
  addExperience,
  addItem,
  advance,
  advanceBrewing,
  advanceCrop,
  advanceCropByBoneMeal,
  advanceFoodTimer,
  applyDamage,
  applyExplosionPlan,
  applyLook,
  applyPrimedTntPlan,
  applyVanillaAnvil,
  calculateEnchantmentTableLevelCost,
  cameraPoseOf,
  canPlantCrop,
  cellAt,
  changed,
  clampFrameDelta,
  clampHotbarIndex,
  clampPitch,
  conflictsIn,
  counterOf,
  countOf,
  countOfKind,
  craftFromGrid,
  craftGrid,
  createWither,
  cropDefinitionFor,
  cropLocationKey,
  cycleHotbarIndex,
  damageEquipment,
  damageWither,
  dayLengthSecs,
  despawnEntity,
  durability,
  durabilityForItem,
  eat,
  EMPTY_STATISTICS,
  emptyBrewingState,
  emptyEquipment,
  emptyFurnaceState,
  emptyInventory,
  emptyRoster,
  emptyVehicleSnapshot,
  ENCHANTMENT_TABLE_BOOK,
  ENCHANTMENT_TABLE_MAX_BOOKSHELVES,
  ENCHANTMENT_TABLE_SLOT_COUNT,
  enchantmentAppliesTo,
  enchantmentRuleFor,
  enchantmentsConflict,
  enchantmentTableCostAtLevel,
  enchantmentTableOutputItemOf,
  enchantmentTableRuleFor,
  ENTITY_ID_PREFIX,
  EntityId,
  EntityKind,
  equip,
  EQUIPMENT_CATALOG,
  EQUIPMENT_SLOTS,
  equipmentDefinitionFor,
  equipmentItem,
  equippedAt,
  exactly,
  EXHAUSTION_PER_POINT,
  EXHAUSTION_PER_REGEN,
  experienceCostOfLevel,
  experienceLevel,
  experienceProgress,
  EYE_LEVEL_OFFSET,
  findEntity,
  FIRST_FRAME_DELTA_SECS,
  FOOD_TICK_SECS,
  forwardVector,
  frameDeltaBetween,
  frameDeltaLossBetween,
  frameDeltaLossSecs,
  generateEnchantmentTableOffers,
  heal,
  HOTBAR_SIZE,
  HOTBAR_START,
  hotbarSlotIndex,
  ingredientMatches,
  INITIAL_PLAYER_POSE,
  INITIAL_TIME_STATE,
  INITIAL_WEATHER_STATE,
  INVENTORY_SLOT_COUNT,
  isCropType,
  isDamageableItemType,
  isDead,
  isDurability,
  isEnchantmentTableRuleId,
  isEntityId,
  isEntityKind,
  isEquipmentItem,
  isEquipmentItemForSlot,
  isEquipmentSlot,
  isEquippableItemType,
  isHotbarIndex,
  isMatureCrop,
  isNight,
  isSupportedVanillaEnchantmentId,
  isUnlocked,
  isValidDurabilityForItem,
  isValidStatistics,
  isValidTimeState,
  isValidVitals,
  isValidWeatherState,
  isWeather,
  ITEM_DURABILITY_CATALOG,
  itemDurabilityDefinitionFor,
  itemEnchantabilityOf,
  itemStack,
  levelForTotalExperience,
  matchRecipe,
  matchSmeltingRecipe,
  matchWitherSummon,
  matureYieldsFor,
  maturitySecsFor,
  MAX_DAY_LENGTH_SECS,
  MAX_EXHAUSTION,
  MAX_FRAME_DELTA_SECS,
  MAX_TIME_FRACTION,
  MAX_TNT_FUSE_ADVANCE_SECS,
  maxStackCountForItem,
  MIN_DAY_LENGTH_SECS,
  MIN_FRAME_DELTA_SECS,
  mintEntityId,
  MOON_PHASE_COUNT,
  moonPhase,
  NETHER_WART_MATURITY_SECS,
  normaliseInventory,
  normaliseRoster,
  normaliseStatistics,
  normaliseTimeState,
  normaliseVitals,
  normaliseWeatherState,
  OccupantId,
  PITCH_EPSILON,
  PITCH_MAX_RADIANS,
  PITCH_MIN_RADIANS,
  placeableBlockFromItem,
  planExplosion,
  planPrimedTnt,
  planVanillaAnvil,
  POTATO_MATURITY_SECS,
  primeTnt,
  record,
  REGEN_HUNGER_THRESHOLD,
  removeItem,
  removeItemAt,
  respawn,
  restoreWither,
  serializeWither,
  serialOfEntityId,
  setDayLength,
  setDayLengthThenTimeOfDay,
  setTimeOfDay,
  shapedRecipe,
  shapelessRecipe,
  slotAt,
  SPAWN_SATURATION,
  SPAWN_VITALS,
  spawnEntity,
  stepWither,
  SUPPORTED_VANILLA_ANVIL_RULE_SET,
  SUPPORTED_VANILLA_BOOK_ANVIL_RULE_SET,
  SUPPORTED_VANILLA_BOOK_ENCHANTMENT_RULES,
  SUPPORTED_VANILLA_ENCHANTMENT_IDS,
  SUPPORTED_VANILLA_ENCHANTMENT_RULES,
  SUPPORTED_VANILLA_ITEM_ANVIL_RULE_SET,
  SUPPORTED_VANILLA_ITEM_ENCHANTMENT_RULES,
  swapEquipment,
  sweepRoster,
  TICKS_PER_SECOND,
  timeOfDay,
  totalExperienceAtLevel,
  UNCHANGED,
  unequip,
  unlock,
  validateCropSnapshot,
  validateEquipmentSnapshot,
  validateVehicleSnapshot,
  VANILLA_ENCHANTMENT_COSTS,
  VANILLA_ENCHANTMENT_TABLE_RULES,
  VehicleId,
  vitalsView,
  WEATHERS,
  WHEAT_MATURITY_SECS,
  WITHER_ARMOUR_THRESHOLD,
  WITHER_FOLLOW_ACCELERATION,
  WITHER_MAX_HEALTH,
  WITHER_MAX_SPEED,
  WITHER_REGEN_PER_SEC,
  WITHER_SPAWN_CHARGE_SECS,
  witherSkullProjectile,
  withFeetPosition,
} from '@nerima-games/mc-sim'
export type {
  AchievementId,
  AddOutcome,
  BehaviourRepair,
  BlockBreakDecision,
  BlockCell,
  BlockPlacementDecision,
  BrewingAdvanceResult,
  BrewingRecipe,
  BrewingState,
  CalculateEnchantmentTableLevelCostInput,
  CameraOrientation,
  CraftGrid,
  CraftOutcome,
  CraftResult,
  CropDefinition,
  CropLocation,
  CropSnapshot,
  CropState,
  CropType,
  CropValidationError,
  CropValidationResult,
  Damage,
  DamageCause,
  DamageEquipmentResult,
  DamageableItemType,
} from '@nerima-games/mc-sim'

export {
  BONE_MEAL_GROWTH_SECS,
  BREWING_BOTTLE_SLOTS,
  BREWING_FUEL_ITEM,
  BREWING_TIME_SECS,
  CROP_REGISTRY,
  CROP_TYPES,
  DEFAULT_DAY_LENGTH_SECS,
  DEFAULT_EXPLOSION_LIMITS,
  DEFAULT_MAX_HEALTH_POINTS,
  DEFAULT_MAX_HUNGER_POINTS,
  DEFAULT_TNT_FUSE_SECS,
  DESPAWNED,
} from '@nerima-games/mc-sim'

// The mc-sim barrel also re-exports the kernel anvil vocabulary.
// Explicit re-exports below pick the owner, mc-kernel.
export type {
  AnvilApplyResult,
  AnvilCustomName,
  AnvilDurability,
  AnvilEnchantment,
  AnvilEnchantmentId,
  AnvilEnchantmentRule,
  AnvilInputStack,
  AnvilItemPayload,
  AnvilPlan,
  AnvilRejectionReason,
  AnvilRepairMaterialRule,
  AnvilRuleSet,
  AnvilSnapshot,
  AnvilSnapshotEncodingResult,
  AnvilSnapshotResult,
  AnvilSnapshotString,
  AnvilState,
  AnvilValidationIssue,
  CanonicalAnvilItemPayload,
  CanonicalAnvilState,
} from '@nerima-games/mc-kernel'
export {
  ANVIL_MAX_CUSTOM_NAME_LENGTH,
  ANVIL_REPAIR_BONUS_RATIO,
  ANVIL_SNAPSHOT_VERSION,
  ANVIL_TOO_EXPENSIVE_LEVEL,
  applyAnvil,
  decodeAnvilSnapshot,
  decodeAnvilSnapshotString,
  encodeAnvilSnapshot,
  isAnvilCustomName,
  isAnvilEnchantmentId,
  isAnvilSnapshotString,
  nextAnvilRepairCost,
  planAnvil,
  snapshotAnvilState,
} from '@nerima-games/mc-kernel'
// Mc-sim also re-exports mc-kernel's settings vocabulary unchanged; pick the
// Same owner, mc-kernel, as the anvil vocabulary above.
export type {
  GraphicsQuality,
  Settings,
} from '@nerima-games/mc-kernel'

export {
  DEFAULT_SETTINGS,
  GRAPHICS_QUALITIES,
  MAX_FOV_DEGREES,
  MAX_MOUSE_SENSITIVITY,
  MAX_RENDER_DISTANCE,
  MAX_VOLUME,
  MIN_FOV_DEGREES,
  MIN_MOUSE_SENSITIVITY,
  MIN_RENDER_DISTANCE,
  MIN_VOLUME,
  applySettings,
  isGraphicsQuality,
  isValidSettings,
  keyBindingFor,
  normaliseSettings,
  rebindKey,
  unbindKey,
} from '@nerima-games/mc-kernel'
// Kit-owned interaction helpers shadow the same-named mc-sim re-exports.
export { breakBlock } from './domain/block-breaking.js'
export { placeBlock } from './domain/block-placement.js'
export * as physics from '@nerima-games/mc-physics'
export * as save from '@nerima-games/mc-save'
export * as worldgen from '@nerima-games/mc-worldgen'
export {
  snapshotAgeSecs,
} from '@nerima-games/mc-sim'
export {
  advanceFurnace,
  collectFurnaceOutput,
} from './domain/furnace-interaction.js'

export * from './application/preview-ports.js'
export * from './application/generated-world-provider.js'
export * from './application/chunk-store-world-sync.js'
export * from './application/world-runtime-snapshot.js'
export * from './application/world-runtime-persistence.js'
export * from './application/gameplay-preview.js'
export * from './application/generated-gameplay.js'
export * from './application/playground.js'
export * from './application/browser-preview.js'
export * from './application/gameplay-services.js'
